# Support Python version
target-version = "py313"

# General settings
line-length = 120 # Max lenhgt
indent-width = 4 # Spaces

# Catalogues to consider when allowing imports from first/third-party sources
src = ["src"]

# Linter settings
[lint]
# Unstable and preliminary rules
preview = true
# Rule apply linter https://docs.astral.sh/ruff/rules/#flake8-async-async
select = [
    "UP",   # pyupgrade
    "I",    # isort
    "E",    # flake8-errors
    "W",    # flake8-warnings
    "F",    # flake8-pyflakes
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "S",    # flake8-bandit
    "BLE",  # flake8-blind-except
    "T20",  # flake8-print
    "T10",  # flake8-debugger
    "PT",   # flake8-pytest-style
    "RUF",  # Ruff
    "DTZ",  # flake8-datetimez
    "ERA",  # eradicate
    "FURB", # refurb
]
# Rule ignore linter https://docs.astral.sh/ruff/rules/#flake8-async-async
ignore = [
    "C408",
    "RUF001",
    "RUF002",
    "RUF003",
    "S110",
]
# Excluding directories and files from linting
exclude = [
    "tests/**",
]
# Errors that can be corrected automatically
fixable = [
    "I", # Import sorting
]

# Format settings
[format]
quote-style = "single" # 'single' | "double"
indent-style = "space"

# Additional settings for plugins
[lint.flake8-bandit]
check-typed-exception = true